# Generated by Django 5.0.4 on 2024-05-10 05:16

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_category_icon_alter_server_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_banner_upload_path,
                validators=[server.validators.validate_image_extension],
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_icon_upload_path,
                validators=[
                    server.validators.validate_image_extension,
                    server.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=server.models.category_icon_upload_path,
                validators=[
                    server.validators.validate_image_extension,
                    server.validators.validate_file_size,
                ],
            ),
        ),
    ]
